import csv
import logging
from functools import lru_cache
from pathlib import Path

from fastapi import FastAPI
from pydantic import BaseModel, Field

from app.config import BERT_MODEL_DIR, RUBRIC_MAX_SCORE
from app.feedback.rule_based import generate_feedback
from app.scoring.sbert_scoring import SBERTScorer
from app.scoring.transformer_scoring import BertRegressorScorer

app = FastAPI()
logger = logging.getLogger("nlp.main")

DATA_DIR = Path(__file__).resolve().parent / "data"
SAMPLE_DATASET_PATH = DATA_DIR / "sample_dataset.csv"


def _load_reference_answers() -> dict[int, str]:
	"""
	Load reference answers mapped by question_id.

	Supported formats:
	- CSV with `question_id,reference_answer`
	- CSV with `question,reference_answer` (question IDs are generated by first-seen order)
	"""
	if not SAMPLE_DATASET_PATH.exists():
		return {}

	mapping: dict[int, str] = {}
	question_to_id: dict[str, int] = {}
	next_id = 1

	with SAMPLE_DATASET_PATH.open("r", encoding="utf-8", newline="") as fp:
		reader = csv.DictReader(fp)
		for row in reader:
			reference = (row.get("reference_answer") or "").strip()
			if not reference:
				continue

			raw_qid = (row.get("question_id") or "").strip()
			if raw_qid:
				try:
					qid = int(raw_qid)
				except ValueError:
					continue
				mapping.setdefault(qid, reference)
				continue

			question_text = (row.get("question") or row.get("question_text") or "").strip()
			if question_text:
				if question_text not in question_to_id:
					question_to_id[question_text] = next_id
					next_id += 1
				mapping.setdefault(question_to_id[question_text], reference)

	return mapping


REFERENCE_ANSWERS = _load_reference_answers()


@lru_cache(maxsize=1)
def get_scorer() -> tuple[str, object]:
	bert_dir = Path(BERT_MODEL_DIR)
	if bert_dir.exists():
		try:
			logger.info("loading bert scorer from %s", bert_dir)
			return "bert", BertRegressorScorer(str(bert_dir))
		except Exception as exc:
			logger.warning("failed to load bert scorer, fallback to sbert: %s", exc)

	logger.info("loading sbert scorer")
	return "sbert", SBERTScorer()


class ScoringRequest(BaseModel):
	question_id: int = Field(gt=0)
	answer_text: str = Field(min_length=1)
	reference_answer: str | None = None

class ScoringResponse(BaseModel):
	score: float
	feedback: str

@app.get("/health")
def health():
	model_type, _ = get_scorer()
	return {"status": "ok", "model_type": model_type}

@app.post("/score", response_model=ScoringResponse)
def score_answer(request: ScoringRequest):
	model_type, scorer = get_scorer()

	if model_type == "bert":
		score = scorer.score(request.answer_text)
		feedback = generate_feedback(score, max_score=RUBRIC_MAX_SCORE)
		return {"score": float(score), "feedback": feedback}

	reference = request.reference_answer or REFERENCE_ANSWERS.get(request.question_id)
	if not reference:
		return {
			"score": 0.0,
			"feedback": "Reference answer unavailable for this question.",
		}

	score = scorer.score(request.answer_text, reference)
	feedback = generate_feedback(score, max_score=1.0)
	return {"score": float(score), "feedback": feedback}
