import csv
import logging
import re
from functools import lru_cache
from pathlib import Path

from fastapi import FastAPI
from pydantic import BaseModel, Field

from app.config import BERT_MODEL_DIR, RUBRIC_MAX_SCORE
from app.feedback.rule_based import generate_feedback
from app.scoring.sbert_scoring import SBERTScorer
from app.scoring.transformer_scoring import BertRegressorScorer

app = FastAPI()
logger = logging.getLogger("nlp.main")

DATA_DIR = Path(__file__).resolve().parent / "data"
SAMPLE_DATASET_PATH = DATA_DIR / "sample_dataset.csv"


def _load_reference_answers() -> dict[int, str]:
	"""
	Load reference answers mapped by question_id.

	Supported formats:
	- CSV with `question_id,reference_answer`
	- CSV with `question,reference_answer` (question IDs are generated by first-seen order)
	"""
	if not SAMPLE_DATASET_PATH.exists():
		return {}

	mapping: dict[int, str] = {}
	question_to_id: dict[str, int] = {}
	next_id = 1

	with SAMPLE_DATASET_PATH.open("r", encoding="utf-8", newline="") as fp:
		reader = csv.DictReader(fp)
		for row in reader:
			reference = (row.get("reference_answer") or "").strip()
			if not reference:
				continue

			raw_qid = (row.get("question_id") or "").strip()
			if raw_qid:
				try:
					qid = int(raw_qid)
				except ValueError:
					continue
				mapping.setdefault(qid, reference)
				continue

			question_text = (row.get("question") or row.get("question_text") or "").strip()
			if question_text:
				if question_text not in question_to_id:
					question_to_id[question_text] = next_id
					next_id += 1
				mapping.setdefault(question_to_id[question_text], reference)

	return mapping


REFERENCE_ANSWERS = _load_reference_answers()


@lru_cache(maxsize=1)
def get_scorer() -> tuple[str, object]:
	bert_dir = Path(BERT_MODEL_DIR)
	if bert_dir.exists():
		try:
			logger.info("loading bert scorer from %s", bert_dir)
			return "bert", BertRegressorScorer(str(bert_dir))
		except Exception as exc:
			logger.warning("failed to load bert scorer, fallback to sbert: %s", exc)

	logger.info("loading sbert scorer")
	return "sbert", SBERTScorer()


@lru_cache(maxsize=1)
def get_reference_scorer() -> SBERTScorer:
	"""Scorer that compares student answer to a reference answer."""
	logger.info("loading reference scorer (sbert)")
	return SBERTScorer()


def _clamp01(value: float) -> float:
	return max(0.0, min(1.0, float(value)))


def _normalize_bert_score(raw_score: float) -> float:
	if RUBRIC_MAX_SCORE <= 0:
		return 0.0
	return _clamp01(raw_score / RUBRIC_MAX_SCORE)


class ScoringRequest(BaseModel):
	question_id: int = Field(gt=0)
	answer_text: str = Field(min_length=1)
	reference_answer: str | None = None

class ScoringResponse(BaseModel):
	score: float
	feedback: str


class GenerateQuestionRequest(BaseModel):
	topic: str = Field(min_length=3, max_length=180)
	difficulty: str = Field(default="intermediate", min_length=3, max_length=32)
	max_score: int = Field(default=5, ge=1, le=10)
	title_hint: str | None = Field(default=None, max_length=255)


class GenerateQuestionResponse(BaseModel):
	title: str
	prompt: str
	reference_answer: str
	max_score: int = Field(ge=1, le=10)


def _normalize_difficulty(raw: str) -> str:
	raw_value = (raw or "").strip().lower()
	if raw_value in {"easy", "beginner", "basic"}:
		return "easy"
	if raw_value in {"hard", "advanced", "expert"}:
		return "hard"
	return "intermediate"


def _topic_keywords(topic: str) -> list[str]:
	parts = re.split(r"[,;/|]", topic)
	keywords = [p.strip() for p in parts if p.strip()]
	if keywords:
		return keywords[:3]
	words = [w for w in re.split(r"\s+", topic.strip()) if w]
	if not words:
		return ["main concept"]
	return [" ".join(words[:2])]


def _build_prompt(topic: str, difficulty: str, keywords: list[str]) -> str:
	if difficulty == "easy":
		return (
			f"Explain the topic '{topic}' in simple terms. Use 2 short paragraphs and "
			"include one practical example. Make sure your answer mentions: "
			f"{', '.join(keywords)}."
		)
	if difficulty == "hard":
		return (
			f"Analyze '{topic}' in depth. Compare at least 2 approaches, discuss trade-offs, "
			"and justify your recommendation with clear reasoning. Ensure your answer covers: "
			f"{', '.join(keywords)}."
		)
	return (
		f"Describe '{topic}' clearly. Structure your response with definition, key ideas, "
		"and one real-world example. Ensure the answer addresses: "
		f"{', '.join(keywords)}."
	)


def _build_reference_answer(topic: str, difficulty: str, keywords: list[str]) -> str:
	base = [
		f"{topic} can be defined clearly with accurate terminology.",
		f"Key ideas include {', '.join(keywords)} and how they interact.",
		"A practical example demonstrates application in a realistic scenario.",
	]
	if difficulty == "hard":
		base.append("The answer compares alternatives and explains trade-offs with justification.")
	elif difficulty == "easy":
		base.append("The explanation is concise, beginner-friendly, and avoids unnecessary jargon.")
	else:
		base.append("The explanation balances conceptual clarity with practical understanding.")
	return " ".join(base)

@app.get("/health")
def health():
	model_type, _ = get_scorer()
	return {"status": "ok", "model_type": model_type}

@app.post("/score", response_model=ScoringResponse)
def score_answer(request: ScoringRequest):
	model_type, scorer = get_scorer()
	reference = request.reference_answer or REFERENCE_ANSWERS.get(request.question_id)

	# Preferred path: score against the reference answer.
	# This prevents low/irrelevant scores when the model sees only student text.
	if reference:
		if model_type == "bert":
			bert_raw = scorer.score(request.answer_text)
			bert_norm = _normalize_bert_score(bert_raw)

			reference_scorer = get_reference_scorer()
			sbert_raw = reference_scorer.score(request.answer_text, reference)
			sbert_norm = _clamp01(sbert_raw)

			# Heavier weight on semantic match to reference.
			score = (0.7 * sbert_norm) + (0.3 * bert_norm)
		else:
			score = _clamp01(scorer.score(request.answer_text, reference))

		feedback = generate_feedback(score, max_score=1.0)
		return {"score": float(score), "feedback": feedback}

	if model_type == "bert":
		score = _normalize_bert_score(scorer.score(request.answer_text))
		feedback = generate_feedback(score, max_score=1.0)
		return {"score": float(score), "feedback": feedback}

	return {
		"score": 0.0,
		"feedback": "Reference answer unavailable for this question.",
	}


@app.post("/generate-question", response_model=GenerateQuestionResponse)
def generate_question(request: GenerateQuestionRequest):
	topic = request.topic.strip()
	difficulty = _normalize_difficulty(request.difficulty)
	keywords = _topic_keywords(topic)

	title = (request.title_hint or "").strip() or f"{topic}: Applied Understanding"
	prompt = _build_prompt(topic, difficulty, keywords)
	reference_answer = _build_reference_answer(topic, difficulty, keywords)

	return {
		"title": title,
		"prompt": prompt,
		"reference_answer": reference_answer,
		"max_score": request.max_score,
	}
